### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by jjgalvez** [gi-lom/gnabel#6]
First very cool program, I hope you keep it up.

The install script is, a bit funky.  Several suggestions.
1) don't hardcode the location of both the icon and the settings file. If they are relative to your gnabel.py file you could get their locations pragmatically.
2) don't put the settings file in the same location as the program as it may not be writable. Either create it at install or put it in a user folder such as .config
3) don't use pip on a system install, it may cause issues with the system managed python, best to use a virtualenv

Also if you're interested I created an arch PKGBUILD which installs gnabel within a virtualenv. I am still using your source code updating which as I said could be eliminated.

**Comment by gi-lom** [comment]
Some contributors have committed an improved version of the script, including some of the modifications you suggested. Have a look at it and tell me if problems still persist, if you can.
I am interested in your Pkgbuild. Where do you have it?

**Comment by fushinari** [comment]
1 and 2 have been addressed in #5 and #7 by @KSXGitHub.

Still, using an install script instead of a proper build system or using setup.py is already a bad idea... If and when this project grows even a little beyond a single-file program, it'll get troublesome to package.

That aside, 3 can be addressed by simply leaving the dependency installation up to the user. I personally think that's the right way to do it. Checking for the dependencies is all that the install script should do. You can use pkgutil to find if a Python module is installed.

**Comment by gi-lom** [comment]
Approve, in fact the script was just a first workaround before I would get more expert with building.
KSXGitHub has made a Pkgbuild and an AUR package, plus another guy has made a Flatpak manifesto

**Comment by rafaelmardojai** [comment]
@gi-lom if you're interested I can make a PR with an initial [Meson](https://mesonbuild.com/) setup.

**Comment by fushinari** [comment]
@rafaelmardojai `pyperclip` is not a dependency anymore btw. (It never was because GTK's native clipboard mechanism is what's actually being used but it was being imported for no reason.) I like the idea of using Meson, lot cleaner.

@KSXGitHub The switch to SVG icons probably broke the xdg-icon-resource installation. IIRC, it supports only PNGs and XPMs. Can you confirm? (This won't be an issue at all if Meson is used)

**Comment by KSXGitHub** [comment]
@fushinari Now that I had made PKGBUILD, I doubt the necessity of `xdg-icon-resource`: In the PKGBUILD, I only need to copy the icon to `/usr/share/icons/hicolor/<size>/apps/gnabel.<extension>`.

**Comment by fushinari** [comment]
> @fushinari Now that I had made PKGBUILD, I doubt the necessity of `xdg-icon-resource`: In the PKGBUILD, I only need to copy the icon to `/usr/share/icons/hicolor/<size>/apps/gnabel.<extension>`.

Yes, for us Arch users, true. But I meant for other distros. Well, not an issue anyway because if meson is used, the install.sh script will be deprecated.

**Comment by KSXGitHub** [comment]
I have made a PR to fix icon installation: https://github.com/gi-lom/gnabel/pull/14

**Comment by gi-lom** [comment]
> @gi-lom if you're interested I can make a PR with an initial [Meson](https://mesonbuild.com/) setup.

I am
